name: Publish package

on:
  push:
    tags: ['*']

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: echo ::set-env name=GIT_TAG::${GITHUB_REF#refs/*/}
      - run: sed -i "s/0.0.0-version-placeholder/${{env.GIT_TAG}}/" package.json
      - run: npm ci
      - run: npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
